// <auto-generated />
using System;
using JuriScraper.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JuriScraper.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240315000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JuriScraper.Domain.Entities.ParteProcesso", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Documento").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Nome").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<int>("ProcessoId").HasColumnType("int");
                b.Property<string>("Tipo").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.HasIndex("ProcessoId");
                b.ToTable("PartesProcesso");
            });

            modelBuilder.Entity("JuriScraper.Domain.Entities.Processo", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Assunto").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Classe").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<DateTime>("DataColeta").HasColumnType("datetime2");
                b.Property<DateTime?>("DataDistribuicao").HasColumnType("datetime2");
                b.Property<DateTime?>("DataUltimoAndamento").HasColumnType("datetime2");
                b.Property<string>("ForoComarca").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("NumeroProcesso").IsRequired().HasColumnType("nvarchar(450)");
                b.Property<string>("Tribunal").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("UltimoAndamento").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.HasIndex("NumeroProcesso").IsUnique();
                b.ToTable("Processos");
            });

            modelBuilder.Entity("JuriScraper.Domain.Entities.ParteProcesso", b =>
            {
                b.HasOne("JuriScraper.Domain.Entities.Processo", "Processo")
                    .WithMany("Partes")
                    .HasForeignKey("ProcessoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Processo");
            });

            modelBuilder.Entity("JuriScraper.Domain.Entities.Processo", b =>
            {
                b.Navigation("Partes");
            });
#pragma warning restore 612, 618
        }
    }
}
